apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmindepl
spec:
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      volumes:
      - name: pg-pvc
        persistentVolumeClaim:
          claimName: pg-pvc
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        args:
        - server
        - /var/lib/pgadmin
        volumeMounts:
        - name: pg-pvc
          mountPath: '/var/lib/pgadmin'
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "akapitan@eva.ua"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "akapitan"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pgadminservice
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: pgadmin
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadminingress
spec:
  rules:
    - host: pg.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgadminservice
                port:
                  number: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi